name: Sync chatgpt/duckduckgpt/ to KudoAI/duckduckgpt/greasemonkey/ & adamlui/ai-web-extensions/duckduckgpt/greasemonkey/

on:
  push:
    branches: [master]
    paths: [chatgpt/duckduckgpt/**]

permissions:
  contents: read

jobs:
  build:
    if: (github.repository == 'adamlui/userscripts') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      TZ: PST8PDT

    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v5
        with:
          path: adamlui/userscripts

      - name: Checkout KudoAI/duckduckgpt
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: KudoAI/duckduckgpt
          path: KudoAI/duckduckgpt

      - name: Checkout adamlui/ai-web-extensions
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/ai-web-extensions
          path: adamlui/ai-web-extensions

      - name: Sync docs/ to KudoAI/duckduckgpt/docs/ & adamlui/ai-web-extensions/duckduckgpt/docs/
        run: |
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/duckduckgpt/docs \
            ${{ github.workspace }}/KudoAI/duckduckgpt/
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/duckduckgpt/docs \
            ${{ github.workspace }}/adamlui/ai-web-extensions/duckduckgpt/

      - name: Sync chatgpt/duckduckgpt/ to KudoAI/duckduckgpt/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/duckduckgpt/ \
            ${{ github.workspace }}/KudoAI/duckduckgpt/greasemonkey/

      - name: Sync chatgpt/duckduckgpt/ to adamlui/ai-web-extensions/duckduckgpt/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/duckduckgpt/ \
            ${{ github.workspace }}/adamlui/ai-web-extensions/duckduckgpt/greasemonkey/

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Config committer
        run: |
          gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
          git config --global commit.gpgsign true
          git config --global user.name "kudo-sync-bot"
          git config --global user.email "auto-sync@kudoai.com"
          git config --global user.signingkey "${{ secrets.GPG_PRIVATE_ID }}"

      - name: Push changes to KudoAI/duckduckgpt
        run: |
          cd ${{ github.workspace }}/KudoAI/duckduckgpt
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from https://github.com/adamlui/userscripts/tree/master/chatgpt/duckduckgpt]" || true
          git push

      - name: Push changes to adamlui/ai-web-extensions
        run: |
          cd ${{ github.workspace }}/adamlui/ai-web-extensions
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from https://github.com/adamlui/userscripts/tree/master/chatgpt/duckduckgpt]" || true
          git push
