name: Sync chatgpt/amazongpt/ to KudoAI/amazongpt/greasemonkey/ & adamlui/ai-web-extensions/amazongpt/greasemonkey/

on:
  push:
    branches: [master]
    paths: [chatgpt/amazongpt/**]

permissions:
  contents: read

jobs:
  build:
    if: (github.repository == 'adamlui/userscripts') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      TZ: PST8PDT

    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v5
        with:
          path: adamlui/userscripts

      - name: Checkout KudoAI/amazongpt
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: KudoAI/amazongpt
          path: KudoAI/amazongpt

      - name: Checkout adamlui/ai-web-extensions
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/ai-web-extensions
          path: adamlui/ai-web-extensions

      - name: Sync docs/ to KudoAI/amazongpt/docs/ && adamlui/ai-web-extensions/amazongpt/docs/
        run: |
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/amazongpt/docs \
            ${{ github.workspace }}/KudoAI/amazongpt/
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/amazongpt/docs \
            ${{ github.workspace }}/adamlui/ai-web-extensions/amazongpt/

      - name: Sync chatgpt/amazongpt/ to KudoAI/amazongpt/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/amazongpt/ \
            ${{ github.workspace }}/KudoAI/amazongpt/greasemonkey/

      - name: Sync chatgpt/amazongpt/ to adamlui/ai-web-extensions/amazongpt/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/amazongpt/ \
            ${{ github.workspace }}/adamlui/ai-web-extensions/amazongpt/greasemonkey/

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Config committer
        run: |
          gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
          git config --global commit.gpgsign true
          git config --global user.name "kudo-sync-bot"
          git config --global user.email "auto-sync@kudoai.com"
          git config --global user.signingkey "${{ secrets.GPG_PRIVATE_ID }}"

      - name: Push changes to KudoAI/amazongpt
        run: |
          cd ${{ github.workspace }}/KudoAI/amazongpt
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from https://github.com/adamlui/userscripts/tree/master/chatgpt/amazongpt]" || true
          git push

      - name: Push changes to adamlui/ai-web-extensions
        run: |
          cd ${{ github.workspace }}/adamlui/ai-web-extensions
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from https://github.com/adamlui/userscripts/tree/master/chatgpt/amazongpt]" || true
          git push
