name: Sync github/github-star-history/ to adamlui/github-star-history/greasemonkey/

on:
  push:
    branches: [master]
    paths: [github/github-star-history/**]

permissions:
  contents: read

jobs:
  build:
    if: (github.repository == 'adamlui/userscripts') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      TZ: PST8PDT

    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v5
        with:
          path: adamlui/userscripts

      - name: Checkout adamlui/github-star-history
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/github-star-history
          path: adamlui/github-star-history

      - name: Sync github/github-star-history/docs/ to adamlui/github-star-history/docs/
        run: |
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/github/github-star-history/docs \
            ${{ github.workspace }}/adamlui/github-star-history/

      - name: Sync github/github-star-history/ to adamlui/github-star-history/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/github/github-star-history/ \
            ${{ github.workspace }}/adamlui/github-star-history/greasemonkey/

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Config committer
        run: |
          gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
          git config --global commit.gpgsign true
          git config --global user.name "kudo-sync-bot"
          git config --global user.email "auto-sync@kudoai.com"
          git config --global user.signingkey "${{ secrets.GPG_PRIVATE_ID }}"

      - name: Push changes to adamlui/github-star-history
        run: |
          cd ${{ github.workspace }}/adamlui/github-star-history
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from https://github.com/adamlui/userscripts/tree/master/github/github-star-history]" || true
          git push
